FROM ghcr.io/geekcodev/php:8.4

ARG INSTALL_XDEBUG=false
RUN if [ ${INSTALL_XDEBUG} = true ]; \
    then \
      pecl install xdebug && docker-php-ext-enable xdebug; \
    fi;

COPY /docker/config/usr/local/etc/php/conf.d/40-custom.ini /usr/local/etc/php/conf.d/40-custom.ini
COPY /docker/config/usr/local/etc/php/conf.d/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini


RUN usermod -u 1000 www-data && groupmod -g 1000 www-data
USER www-data:www-data

WORKDIR /var/www/html

EXPOSE 9000
CMD ["php-fpm"]