FROM node:25.4-bookworm
WORKDIR /var/www/html
ADD docker/scripts/docker-node-entrypoint.sh /usr/bin/docker-node-entrypoint.sh
RUN ["chmod", "+x", "/usr/bin/docker-node-entrypoint.sh"]
ENTRYPOINT [ "/usr/bin/docker-node-entrypoint.sh" ]
