# Dockerfile_app_dev

FROM node:25-alpine3.22 AS node_builder
LABEL stage=builder
WORKDIR /builder

COPY /app/package.json /builder/package.json
COPY /app/package-lock.json /builder/package-lock.json
COPY /app/vite.config.ts /builder/vite.config.ts
COPY /app/tailwind.config.js /builder/tailwind.config.js

RUN npm ci

COPY /app/resources /builder/resources
RUN npm run build


FROM ghcr.io/geekcodev/php:8.4 AS php_builder
LABEL stage=builder
WORKDIR /build

COPY /app/composer.json /app/composer.lock ./
RUN composer install --optimize-autoloader

COPY /app .


FROM ghcr.io/geekcodev/php:8.4

COPY /docker/config/usr/local/etc/php/conf.d/40-custom.app.ini /usr/local/etc/php/conf.d/40-custom.ini

RUN usermod -u 1000 www-data && groupmod -g 1000 www-data
USER www-data:www-data

WORKDIR /var/www/html

COPY --from=php_builder --chown=www-data:www-data /build/vendor ./vendor
COPY --from=node_builder --chown=www-data:www-data /builder/public/build ./public/build
COPY --chown=www-data:www-data /app .
COPY --chown=www-data:www-data /app/.env.example .env

RUN php artisan key:generate

EXPOSE 9000
CMD ["php-fpm"]