FROM ghcr.io/geekcodev/php:8.4

COPY /docker/config/usr/local/etc/php/conf.d/40-custom.app.ini /usr/local/etc/php/conf.d/40-custom.ini

RUN usermod -u 1000 www-data && groupmod -g 1000 www-data
USER www-data:www-data

WORKDIR /var/www/html

EXPOSE 9000
CMD ["php-fpm"]
